In [50]:
import numpy as np
import pandas as pd

#importing the dataset from .csv file
df = pd.read_csv('iris.csv', names =['x1','x2','x3','x4','y'], skiprows = 1)
y1 = df['y'].values
# converting the labels to integer values.
label = {'Iris-setosa': 1,'Iris-versicolor': 2,'Iris-virginica': 3}
y1 = [label[item] for item in y1]

x11 = df['x1'].values
x22 = df['x2'].values 
x33 = df['x3'].values 
x44 = df['x4'].values 

#initialize X with parameters:x11,x22,x33,x44
X = np.matrix([np.ones(150),x11,x22,x33,x44]).T

#initialize Y with labels
Y = np.matrix(y1).T


#Finding the b values using b=(X’X)^-1(X’Y)
B=np.dot((np.dot(X.T,X)).I,(np.dot(X.T,Y)))
print("****************************************************************")
print("Beta Values{bo,b1,b2,b3,b4}:")
print(B)
print("****************************************************************")

#initialize Y_caps = Xb
Y_caps = np.dot(X,B)


XTrain = []
YTrain = []
XTest = []
YTest = []
accuracy = []

#Splitting the data for cross-validation
SplitX = np.split(X,5)
SplitY = np.split(Y,5)

# K-fold for k=5
for i in range(0,len(SplitX)):
    for j in range(0,len(SplitY)):
        if j == i:
            XTest.append(SplitX[j])
            YTest.append(SplitY[j])
        else:
            XTrain.append(SplitX[j])
            YTrain.append(SplitY[j])
    # data splitting for training and testing
    XT=np.matrix(np.concatenate(np.array(XTrain)))
    YT=np.matrix(np.concatenate(np.array(YTrain)))
    XTT=np.matrix(np.array(XTest))
    YTT=np.matrix(np.array(YTest)).flatten()

    #finding the b,y_cap and error for each fold.
    b=np.dot((np.dot(XT.T,XT)).I,(np.dot(XT.T,YT)))
    y_caps = np.dot(XTT,b).T.round()
    error=(YTT - y_caps)
    e=error.astype(int)
    #finding Root-mean-square Error for the fold
    rmse =np.sqrt(np.sum(np.square(YTT - y_caps))/30)  
    print("****************************************************************")
    print("fold:",i+1)
    print("Shape of Y(actual):",YTT.shape)
    print(YTT)
    print("Shape of X:",XTT.shape)
    print("Shape of b:",b.shape)
    print("Shape of Y_cap(Predicted):",y_caps.shape)
    print(y_caps.astype(int))
    
    accuracy.append(1-(np.count_nonzero(e)/30))
    print("Accuracy after each fold")
    print(accuracy)
    print("Root-mean-square Error for the fold:",rmse)
    
    error=np.array([])
    XTrain.clear()
    YTrain.clear()
    XTest.clear()
    YTest.clear()
    
    #finding accuracy and error for the system
    avg = sum(accuracy)/len(accuracy)*100
    eavg = 100 - avg
    print("****************************************************************")
print("System's accuracy(%):",avg)
print("System's error(%):",eavg)

****************************************************************
Beta Values{bo,b1,b2,b3,b4}:
[[ 1.19208399]
 [-0.10974146]
 [-0.04424045]
 [ 0.22700138]
 [ 0.60989412]]
****************************************************************
****************************************************************
fold: 1
Shape of Y(actual): (1, 30)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
Shape of X: (30, 5)
Shape of b: (5, 1)
Shape of Y_cap(Predicted): (1, 30)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
Accuracy after each fold
[1.0]
Root-mean-square Error for the fold: 0.0
****************************************************************
****************************************************************
fold: 2
Shape of Y(actual): (1, 30)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]]
Shape of X: (30, 5)
Shape of b: (5, 1)
Shape of Y_cap(Predicted): (1, 30)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]]
Accuracy after each fo

In [ ]:
# print(df.head())
# print(df.y)
# df.y = [label[item] for item in df.y]
# print(type(y1))
# print(y1)
# print(x11)
# print(x22)
# print(x33)
# print(x44)
# y11 = []
# y11.append(y1)
# print(X)
# print(Y)
# print(Y_caps)
# print(SplitX)
#     XT=np.matrix(np.array(XTrain))
#     YT=np.matrix(np.array(YTrain))
#     print(XT)
#     print(YT)
#     print(XTT)
#     print(YTT)
#     print(y_caps)
#     print(YTT.astype(float))
#     print(YTT.shape)
#     print("___")
#     print(y_caps.shape)
